POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/5366fc5c-28f0-440b-a457-31406bd8d1a7
Content-Type: application/json

{
    "title": "Video node alterado",
    "description": "Esse é o node video editado",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/5366fc5c-28f0-440b-a457-31406bd8d1a7